# Generated by Django 2.1.5 on 2019-03-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.IntegerField()),
                ('total_no_of_stops', models.IntegerField()),
                ('enter_stop_price_time_with_commas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_stop', models.CharField(max_length=128)),
                ('end_stop', models.CharField(max_length=128)),
                ('amount', models.IntegerField(max_length=254)),
            ],
        ),
    ]
