# Generated by Django 2.1.5 on 2019-03-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_ml_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_data',
            name='delay',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
