# Generated by Django 2.1.5 on 2019-03-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_ml_data_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_data',
            name='delay',
            field=models.DateTimeField(),
        ),
    ]
