# Generated by Django 2.1.5 on 2019-03-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20190319_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ml_data',
            name='delay',
        ),
    ]
