# Generated by Django 2.1.5 on 2019-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_remove_ml_data_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_data',
            name='delay',
            field=models.TimeField(default='wer'),
        ),
    ]
