# Generated by Django 2.1.5 on 2019-03-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0010_remove_ml_data_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_data',
            name='delay',
            field=models.TextField(default='20:00'),
        ),
    ]
