# Generated by Django 2.1.7 on 2019-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0012_auto_20190319_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
