# Generated by Django 2.1.7 on 2019-04-03 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0015_user_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='enter_time_with_commas',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='timec',
            field=models.TimeField(default=datetime.datetime.today),
        ),
    ]
