# Generated by Django 2.1.7 on 2019-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0016_auto_20190403_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='total_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
