# Generated by Django 2.1.7 on 2019-04-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0018_remove_bar_enter_time_with_commas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='enter_time_with_commas',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
