# Generated by Django 2.1.7 on 2019-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0020_auto_20190403_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='enter_time',
            field=models.TextField(),
        ),
    ]
