# Generated by Django 2.1.7 on 2019-04-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0021_auto_20190403_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='total_people',
            new_name='total_peo',
        ),
    ]
