# Generated by Django 2.1.7 on 2019-04-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0022_auto_20190403_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_peo',
        ),
    ]
