# Generated by Django 2.1.7 on 2019-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0023_remove_user_total_peo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_peo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
