# Generated by Django 2.1.7 on 2019-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0024_user_total_peo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='stop',
            field=models.CharField(max_length=128),
        ),
    ]
