# Generated by Django 2.1.7 on 2019-04-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0025_auto_20190403_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notif',
            new_name='notifi',
        ),
    ]
