# Generated by Django 2.1.7 on 2019-04-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0026_auto_20190403_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifi',
            new_name='Notifications',
        ),
    ]
