# Generated by Django 2.1.7 on 2019-04-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0027_auto_20190403_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
