# Generated by Django 2.1.7 on 2019-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0028_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=128)),
            ],
        ),
    ]
