# Generated by Django 2.1.7 on 2019-04-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0029_notifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='enter_time',
            field=models.TextField(blank=True),
        ),
    ]
