# Generated by Django 2.1.7 on 2019-05-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0030_auto_20190403_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_data',
            name='time_of_day',
            field=models.TimeField(default='20:00'),
        ),
    ]
