# Generated by Django 2.1.7 on 2019-05-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0032_auto_20190517_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ml_data',
            name='time_of_day',
        ),
    ]
