# Generated by Django 2.1.7 on 2019-05-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0034_ml_data_time_of_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ml_data',
            name='time_of_day',
        ),
    ]
