# Generated by Django 2.1.7 on 2019-07-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0036_ml_data_time_of_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='seats',
            new_name='Seats',
        ),
    ]
